# BACK-END: SERVICE - LOAD BALANCER / NODE PORT
apiVersion: v1
kind: Service
metadata:
  name: php
spec:
  selector:
    app: php
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30005
  # type: LoadBalancer
  type: NodePort

---

# DB: SERVICE - CLUSTERIP
apiVersion: v1
kind: Service
metadata:
  name: mysql-connection
spec:
  ports:
  - port: 3306
  selector:
    app: mysql
  clusterIP: None