stages:
  - build
  - deploy

build_images:
  stage: build
  image: docker:20.10.16

  services:
    - docker:20.10.16-dind

  variables:
    DOCKER_TLS_CERTDIR: "/certs"

  before_script:
    - docker login -u $DOCKERHUB_USER -p $DOCKERHUB_PASSWORD
  
  script:
    - docker build -t pedroheeger/boot015_app-cicd:1.0 app/.
    - docker push pedroheeger/boot015_app-cicd:1.0

deploy:
  stage: deploy

  script:
    - echo "$KEYPAIR_CONTENT" > key.pem
    - chmod 600 key.pem
    - ssh -o StrictHostKeyChecking=no -i key.pem ubuntu@54.227.152.137 "kubectl apply -f /home/ubuntu/cicd/deployment.yml"
    - ssh -o StrictHostKeyChecking=no -i key.pem ubuntu@54.227.152.137 "if lsof -i :8080 > /dev/null 2>&1; then echo "A porta 8080 já está em uso!"; else nohup kubectl port-forward --address 0.0.0.0 service/app-service 8080:80 > /dev/null 2>&1 & disown; fi"