stages:
  - build
  - deploy

build_images:
  stage: build
  image: docker:20.10.16

  services:
    - docker:20.10.16-dind

  variables:
    DOCKER_TLS_CERTDIR: "/certs"

  before_script:
    - docker login -u $DOCKERHUB_USER -p $DOCKERHUB_PASSWORD
  
  script:
    - dcoker build -t pedroheeger/boot015_app-cicd:1.0 app/.
    - docker push pedroheeger/boot015_app-cicd:1.0

deploy:
  stage: deploy

  script:
    - kubectl config use-context minikube
    - kubectl apply -f deployment.yml
    - kubectl set image deployment/your-deployment-name your-container-name=pedroheeger/boot015_app-cicd:1.0
